### 1. Vytvoř bucket
POST http://localhost:8000/buckets/
#X-User-id: -- alice volitelny atribut defaultne anonymous
Content-Type: application/json
{
    "name": "bandwith-bucket"
}
### 2. Nahraj soubor do bucketu (zvýší bandwidth o velikost souboru) #! uloz id daneho souboru pro jeho vypis !#
POST http://localhost:8000/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="test_file.txt"
Content-Type: text/plain

< ./test_file.txt
------WebKitFormBoundary
Content-Disposition: form-data; name="bucket_id"

1
------WebKitFormBoundary--
### 3. Zobraz billing po uploadu
GET http://localhost:8000/buckets/1/billing/
### 4. Stáhni soubor (zvýší bandwidth o velikost souboru) 
##nutno zmenit id souboru
GET http://localhost:8000/files/c67ecc26-7bb0-4ee3-8100-ec468243f72f
### 5. Zobraz billing po downloadu (bandwidth by měl být 2x)
GET http://localhost:8000/buckets/1/billing/
### 6. Zobraz seznam souborů v bucketu
GET http://localhost:8000/buckets/1/objects/