"""bandwith migration

Revision ID: 85d9ca8e9e3b
Revises: f9f3495c6657
Create Date: 2026-04-12 18:11:09.312837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d9ca8e9e3b'
down_revision: Union[str, Sequence[str], None] = 'f9f3495c6657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buckets', sa.Column('bandwidth_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buckets', 'bandwidth_bytes')
    # ### end Alembic commands ###
