"""Pridani soft delete

Revision ID: 8bcedfdd84f5
Revises: e4fddf0d8373
Create Date: 2026-04-13 23:24:00.726418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcedfdd84f5'
down_revision: Union[str, Sequence[str], None] = 'e4fddf0d8373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'is_deleted')
    # ### end Alembic commands ###
